name: Generate Snake Animation

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: milanh34
          outputs: |
            ./dist/github-contribution-grid-snake.svg
          color_snake: '#00FFAA'
          color_dots: '#444444,#2e2e2e,#1e1e1e,#000000'
          background: '#000000'
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
